window.TRAIL_CONFIG = {
  "brandsData": [
    {
      "targetIndex": 0,
      "panel": "Painel 01",
      "trailStep": 1,
      "feature": "custom",
      "targetImage": "targets/source/painel-01/target-1-grupo-tsa.png",
      "name": "Grupo TSA",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 10,
          "duration": 2000,
          "text": "Comunicação Digital",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.4,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 100,
          "duration": 3000,
          "words": [
            "Ecossistema",
            "Tecnologia",
            "Soluções integradas"
          ],
          "animation": "vortex",
          "layout": "circle",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "image": "assets/images/painel-01/image-1-grupo-tsa-3-image.png",
          "title": "POST",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "assets/models/painel-01/model-1-grupo-tsa-3-model3d.glb",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 30,
      "collection": [
        {
          "name": "TSA",
          "title": "TSA",
          "image": "assets/collections/painel-01/1-grupo-tsa-3-carousel3d-1-tsa.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "TSA Digital",
          "title": "TSA Digital",
          "image": "assets/collections/painel-01/1-grupo-tsa-3-carousel3d-2-tsa-digital.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Lynx Process",
          "title": "Lynx Process",
          "image": "assets/collections/painel-01/1-grupo-tsa-3-carousel3d-3-lynx-process.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 1,
      "panel": "Painel 01",
      "trailStep": 2,
      "feature": "custom",
      "targetImage": "targets/source/painel-01/target-2-marca-02.png",
      "name": "Marca 02",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Ambiente digital interno",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Integração",
            "Tecnologia",
            "Antecipamos tendências"
          ],
          "animation": "vortex",
          "layout": "diagonal",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "image": "",
          "title": "BACKGROUND TEAMS",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "assets/models/painel-01/model-2-marca-02-3-model3d.glb",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 2,
      "panel": "Painel 01",
      "trailStep": 3,
      "feature": "custom",
      "targetImage": "targets/source/painel-01/target-3-marca-03.png",
      "name": "Marca 03",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Elementos da Marca",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Qualidade",
            "Tecnologia",
            "Inovação"
          ],
          "animation": "vortex",
          "layout": "column",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "orbit",
          "radius": 0.4,
          "speed": 25,
          "focusAnimation": false,
          "stackInterval": 1700,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 2.15,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "CORES",
              "title": "CORES",
              "image": "assets/collections/painel-01/3-marca-03-3-carousel3d-1-cores.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "ELEMENTOS",
              "title": "ELEMENTOS",
              "image": "assets/collections/painel-01/3-marca-03-3-carousel3d-2-elementos.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "MARCA",
              "title": "MARCA",
              "image": "assets/collections/painel-01/3-marca-03-3-carousel3d-3-marca.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "CORES",
          "title": "CORES",
          "image": "assets/collections/painel-01/3-marca-03-3-carousel3d-1-cores.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "ELEMENTOS",
          "title": "ELEMENTOS",
          "image": "assets/collections/painel-01/3-marca-03-3-carousel3d-2-elementos.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "MARCA",
          "title": "MARCA",
          "image": "assets/collections/painel-01/3-marca-03-3-carousel3d-3-marca.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 3,
      "panel": "Painel 01",
      "trailStep": 4,
      "feature": "custom",
      "targetImage": "targets/source/painel-01/target-4-marca-04.png",
      "name": "Marca 04",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Materiais Institucionais",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.3,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Tecnologia",
            "Ecossistema",
            "Soluções"
          ],
          "animation": "vortex",
          "layout": "grid",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "stack",
          "radius": 0.82,
          "speed": 18,
          "focusAnimation": false,
          "stackInterval": 1500,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 2.15,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "ASSINATURA",
              "title": "ASSINATURA",
              "image": "assets/collections/painel-01/4-marca-04-3-carousel3d-1-assinatura.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "CAPA POWERPOINT",
              "title": "CAPA POWERPOINT",
              "image": "assets/collections/painel-01/4-marca-04-3-carousel3d-2-capa-powerpoint.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "ASSINATURA",
          "title": "ASSINATURA",
          "image": "assets/collections/painel-01/4-marca-04-3-carousel3d-1-assinatura.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "CAPA POWERPOINT",
          "title": "CAPA POWERPOINT",
          "image": "assets/collections/painel-01/4-marca-04-3-carousel3d-2-capa-powerpoint.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 4,
      "panel": "TSA",
      "trailStep": 1,
      "feature": "custom",
      "targetImage": "targets/source/tsa/target-1-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Comunicação Digital",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Múltiplas competências",
            "Tecnologia",
            "Soluções integradas"
          ],
          "animation": "wave",
          "layout": "circle",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": true,
          "delay": 0,
          "duration": 0,
          "image": "assets/images/tsa/image-1-nova-ilha-3-image.png",
          "title": "Modelos de posts",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 8,
      "panel": "DIGITAL",
      "trailStep": 1,
      "feature": "custom",
      "targetImage": "targets/source/digital/target-1-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Comunicação Digital",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Manutenção inteligente",
            "Tecnologia",
            "Gestão de ativos"
          ],
          "animation": "constellation",
          "layout": "circle",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "image": "assets/images/digital/image-1-nova-ilha-3-image.png",
          "title": "",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 12,
      "panel": "LYNX",
      "trailStep": 1,
      "feature": "custom",
      "targetImage": "targets/source/lynx/target-1-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Comunicação Digital",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Autônomos",
            "Otimização",
            "Logística"
          ],
          "animation": "spiral",
          "layout": "circle",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(0, 0, 255)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "image": "assets/images/lynx/image-1-nova-ilha-3-image.png",
          "title": "Modelos de posts 2 (3D)",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 5,
      "panel": "TSA",
      "trailStep": 2,
      "feature": "custom",
      "targetImage": "targets/source/tsa/target-2-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": " Ambiente digital interno",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Consultoria",
            "Tecnologia",
            "Operação"
          ],
          "animation": "wave",
          "layout": "column",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "orbit",
          "radius": 0.82,
          "speed": 18,
          "focusAnimation": false,
          "stackInterval": 1700,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 1.34,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "Wallpaper computador",
              "title": "Wallpaper computador",
              "image": "assets/collections/tsa/2-nova-ilha-3-carousel3d-1-wallpaper-computador.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Fundo Teams",
              "title": "Fundo Teams",
              "image": "assets/collections/tsa/2-nova-ilha-3-carousel3d-2-fundo-teams.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "Wallpaper computador",
          "title": "Wallpaper computador",
          "image": "assets/collections/tsa/2-nova-ilha-3-carousel3d-1-wallpaper-computador.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Fundo Teams",
          "title": "Fundo Teams",
          "image": "assets/collections/tsa/2-nova-ilha-3-carousel3d-2-fundo-teams.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 6,
      "panel": "TSA",
      "trailStep": 3,
      "feature": "custom",
      "targetImage": "targets/source/tsa/target-3-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Comunicação de lançamento",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Confiabilidade",
            "Tecnologia",
            "Operações seguras"
          ],
          "animation": "wave",
          "layout": "diagonal",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "image": "assets/images/tsa/image-3-nova-ilha-3-image.png",
          "title": "Móbiles de teto",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "tilt",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 7,
      "panel": "TSA",
      "trailStep": 4,
      "feature": "custom",
      "targetImage": "targets/source/tsa/target-4-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Materiais Institucionais",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "DESAFIO",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Tecnologia",
            "Ecossistema",
            "Soluções"
          ],
          "animation": "wave",
          "layout": "circle",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "orbit",
          "radius": 0.6,
          "speed": 30,
          "focusAnimation": false,
          "stackInterval": 1700,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 1.34,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "PPT",
              "title": "PPT",
              "image": "assets/collections/tsa/4-nova-ilha-2-carousel3d-1-ppt.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Anúncios de revista",
              "title": "Anúncios de revista",
              "image": "assets/collections/tsa/4-nova-ilha-2-carousel3d-2-anuncios-de-revista.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Assinatura de e-mail ",
              "title": "Assinatura de e-mail ",
              "image": "assets/collections/tsa/4-nova-ilha-2-carousel3d-3-assinatura-de-e-mail.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "PPT",
          "title": "PPT",
          "image": "assets/collections/tsa/4-nova-ilha-2-carousel3d-1-ppt.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Anúncios de revista",
          "title": "Anúncios de revista",
          "image": "assets/collections/tsa/4-nova-ilha-2-carousel3d-2-anuncios-de-revista.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Assinatura de e-mail ",
          "title": "Assinatura de e-mail ",
          "image": "assets/collections/tsa/4-nova-ilha-2-carousel3d-3-assinatura-de-e-mail.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 9,
      "panel": "DIGITAL",
      "trailStep": 2,
      "feature": "custom",
      "targetImage": "targets/source/digital/target-2-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Ambiente digital interno",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Monitoramento",
            "Tecnologia",
            "Disponibilidade"
          ],
          "animation": "constellation",
          "layout": "column",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "orbit",
          "radius": 0.82,
          "speed": 18,
          "focusAnimation": false,
          "stackInterval": 1700,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 1.34,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "Wallpaper computador ",
              "title": "Wallpaper computador ",
              "image": "assets/collections/digital/2-nova-ilha-2-carousel3d-1-wallpaper-computador.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Fundo Teams (3D)",
              "title": "Fundo Teams (3D)",
              "image": "assets/collections/digital/2-nova-ilha-2-carousel3d-2-fundo-teams-3d.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "Wallpaper computador ",
          "title": "Wallpaper computador ",
          "image": "assets/collections/digital/2-nova-ilha-2-carousel3d-1-wallpaper-computador.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Fundo Teams (3D)",
          "title": "Fundo Teams (3D)",
          "image": "assets/collections/digital/2-nova-ilha-2-carousel3d-2-fundo-teams-3d.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 10,
      "panel": "DIGITAL",
      "trailStep": 3,
      "feature": "custom",
      "targetImage": "targets/source/digital/target-3-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Comunicação de lançamento",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Preditiva",
            "Tecnologia",
            "Produtividade"
          ],
          "animation": "constellation",
          "layout": "grid",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "image",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "image": "assets/images/digital/image-3-nova-ilha-2-image.png",
          "title": "•\tMóbiles de teto (3D) – só DIGITAL frente e verso Grupo TSA",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#ffffff",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "interactions": [
            "float",
            "pulse",
            "glow"
          ],
          "spinSpeed": 42,
          "floatAmount": 0.06
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 11,
      "panel": "DIGITAL",
      "trailStep": 4,
      "feature": "custom",
      "targetImage": "targets/source/digital/target-4-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Materiais Institucionais",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Tecnologia",
            "Ecossistema",
            "Soluções"
          ],
          "animation": "constellation",
          "layout": "diagonal",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "orbit",
          "radius": 0.82,
          "speed": 18,
          "focusAnimation": false,
          "stackInterval": 1700,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 1.34,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "PPT 2  (3D)",
              "title": "PPT 2  (3D)",
              "image": "assets/collections/digital/4-nova-ilha-1-carousel3d-1-ppt-2-3d.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Anúncios de revista 2 (3D)",
              "title": "Anúncios de revista 2 (3D)",
              "image": "assets/collections/digital/4-nova-ilha-1-carousel3d-2-anuncios-de-revista-2-3d.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Assinatura de e-mail 2 (3D)",
              "title": "Assinatura de e-mail 2 (3D)",
              "image": "assets/collections/digital/4-nova-ilha-1-carousel3d-3-assinatura-de-e-mail-2-3d.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "PPT 2  (3D)",
          "title": "PPT 2  (3D)",
          "image": "assets/collections/digital/4-nova-ilha-1-carousel3d-1-ppt-2-3d.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Anúncios de revista 2 (3D)",
          "title": "Anúncios de revista 2 (3D)",
          "image": "assets/collections/digital/4-nova-ilha-1-carousel3d-2-anuncios-de-revista-2-3d.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Assinatura de e-mail 2 (3D)",
          "title": "Assinatura de e-mail 2 (3D)",
          "image": "assets/collections/digital/4-nova-ilha-1-carousel3d-3-assinatura-de-e-mail-2-3d.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 13,
      "panel": "LYNX",
      "trailStep": 2,
      "feature": "custom",
      "targetImage": "targets/source/lynx/target-2-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Ambiente digital interno",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Tecnologia",
            "Rastreabilidade",
            "Agilidade"
          ],
          "animation": "spiral",
          "layout": "column",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 14,
      "panel": "LYNX",
      "trailStep": 3,
      "feature": "custom",
      "targetImage": "targets/source/lynx/target-3-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Comunicação de lançamento",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Eficiência",
            "Tecnologia",
            "Sustentabilidade"
          ],
          "animation": "spiral",
          "layout": "diagonal",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    },
    {
      "targetIndex": 15,
      "panel": "LYNX",
      "trailStep": 4,
      "feature": "custom",
      "targetImage": "targets/source/lynx/target-4-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "logoText",
          "order": 1,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 1600,
          "text": "Materiais Institucionais",
          "x": 0,
          "y": 0,
          "width": 1.45,
          "height": 0.24,
          "bg": "rgba(177,18,27,0.72)",
          "color": "#ffffff",
          "font": 60
        },
        {
          "type": "words",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 5000,
          "words": [
            "Tecnologia",
            "Ecossistema",
            "Soluções"
          ],
          "animation": "spiral",
          "layout": "grid",
          "backdropEffect": false,
          "fireflyEffect": true,
          "wordBg": "rgba(177,18,27,0.72)",
          "wordColor": "#ffffff",
          "wordFont": 56
        },
        {
          "type": "carousel3d",
          "order": 3,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0,
          "title": "",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 50,
          "animation": "orbit",
          "radius": 0.82,
          "speed": 18,
          "focusAnimation": false,
          "stackInterval": 1700,
          "stackDepth": 0.18,
          "stackOffsetY": 0.055,
          "focusScale": 1.34,
          "focusY": 0.04,
          "focusZ": 0.72,
          "focusSpinDuration": 1200,
          "focusHoldDuration": 900,
          "itemWidth": 0.52,
          "itemHeight": 0.68,
          "cardBg": "#ffffff",
          "itemTitleBg": "rgba(177,18,27,0.72)",
          "itemTitleColor": "#ffffff",
          "itemTitleFont": 38,
          "modelSize": 0.46,
          "y": 0.05,
          "items": [
            {
              "name": "PPT  3 (3D)",
              "title": "PPT  3 (3D)",
              "image": "assets/collections/lynx/4-nova-ilha-1-carousel3d-1-ppt-3-3d.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": "Anúncios de revista 3 (3D)",
              "title": "Anúncios de revista 3 (3D)",
              "image": "assets/collections/lynx/4-nova-ilha-1-carousel3d-2-anuncios-de-revista-3-3d.png",
              "model": "",
              "modelScale": ""
            },
            {
              "name": " Assinatura de e-mail 3",
              "title": " Assinatura de e-mail 3",
              "image": "assets/collections/lynx/4-nova-ilha-1-carousel3d-3-assinatura-de-e-mail-3.png",
              "model": "",
              "modelScale": ""
            }
          ]
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": [
        {
          "name": "PPT  3 (3D)",
          "title": "PPT  3 (3D)",
          "image": "assets/collections/lynx/4-nova-ilha-1-carousel3d-1-ppt-3-3d.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": "Anúncios de revista 3 (3D)",
          "title": "Anúncios de revista 3 (3D)",
          "image": "assets/collections/lynx/4-nova-ilha-1-carousel3d-2-anuncios-de-revista-3-3d.png",
          "model": "",
          "modelScale": ""
        },
        {
          "name": " Assinatura de e-mail 3",
          "title": " Assinatura de e-mail 3",
          "image": "assets/collections/lynx/4-nova-ilha-1-carousel3d-3-assinatura-de-e-mail-3.png",
          "model": "",
          "modelScale": ""
        }
      ]
    },
    {
      "targetIndex": 16,
      "panel": "Painel 01",
      "trailStep": 5,
      "feature": "custom",
      "targetImage": "targets/source/painel-01/target-5-nova-ilha.png",
      "name": "Nova ilha",
      "steps": [
        {
          "type": "custom",
          "order": 1,
          "stepTitle": "GRUPO TSA",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": false,
          "delay": 0,
          "duration": 0
        },
        {
          "type": "videoPlayer",
          "order": 2,
          "stepTitle": "",
          "stepTitleBg": "rgba(177,18,27,0.72)",
          "stepTitleColor": "#ffffff",
          "stepTitleFont": 64,
          "scratchEffect": true,
          "delay": 0,
          "duration": 0,
          "video": "videos/painel-01/video-5-nova-ilha-2-videoplayer.mp4",
          "title": "",
          "width": 0.82,
          "height": 0.56,
          "x": 0,
          "y": 0.05,
          "z": 0.28,
          "bg": "#000000",
          "titleBg": "rgba(177,18,27,0.72)",
          "titleColor": "#ffffff",
          "titleFont": 38,
          "floatAmount": 0.04,
          "muted": true,
          "loop": true
        }
      ],
      "video": "",
      "site": "",
      "model": "",
      "modelScale": "0.55 0.55 0.55",
      "spinSpeed": 45,
      "collection": []
    }
  ],
  "productTargetsData": [
    {
      "id": "camisa",
      "targetIndex": 4,
      "name": "Camisa TSA",
      "model": "assets/models/marca_01/camisa.glb",
      "spinSpeed": 45
    },
    {
      "id": "bone",
      "targetIndex": 5,
      "name": "Boné TSA",
      "model": "assets/models/marca_01/bone.glb",
      "spinSpeed": 45
    },
    {
      "id": "chaveiro",
      "targetIndex": 6,
      "name": "Chaveiro TSA",
      "model": "assets/models/marca_01/chaveiro.glb",
      "spinSpeed": 48
    }
  ]
};
